const MIN_REWARD_POINTS = 1;
const MAX_REWARD_POINTS = 2;
const MIN_TRANSACTION_TO_REWARD = 50;
const MAX_TRANSACTION_TO_REWARD = 100;
const MONTHS = ["08", "09", "10"];

export {
  MIN_TRANSACTION_TO_REWARD,
  MAX_TRANSACTION_TO_REWARD,
  MIN_REWARD_POINTS,
  MAX_REWARD_POINTS,
  MONTHS
};
